ArtyProd/urls.py
import statistics
from django.contrib import admin
from django.urls import path
from.import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
urlpatterns = [

    #contact
    path('contact',views.contact,name='contact'),
    #--------------------------------DEMANDE PROJET---------------------------------------
    path('demande_projet/', views.demande_projet, name='demande_projet'),
    path('demande_projet_list/', views.demande_projet_list, name='demande_projet_list'),
    path('demande_projet/<int:demande_projet_id>/edit/', views.modifier_demande_projet, name='modifier_demande_projet'),
    path('demande_projet/<int:demande_projet_id>/delete/', views.supprimer_demande_projet, name='supprimer_demande_projet'),

    path('service/', views.Service, name='service'),
    path('contact/', views.contact, name='contact'),
    


    path('personnel/', views.personnel, name='personnel'),
    path('TtPersonnel/', views.TtPersonnel, name='TtPersonnel'),
    path('deletePersonnel/<int:pk>/', views.delete_personnel, name='delete_personnel'),
    path('Personnel/<int:prs_id>/', views.detail_personnel, name='detail_personnel'),
    path('editPersonnem/<int:pk>/', views.edit_personnel, name='edit_personnel'),
    
    path('Projets', views.TtProjet, name='TtProjet'),
    path('createProjet/', views.projet, name='projet'),
    path('<int:proj_id>/detailProjet/', views.detail_projet, name='detail_projet'),
    path('<int:proj_id>/editProjet/', views.edit_projet, name='edit_projet'),
    path('<int:proj_id>/deleteProjet/', views.delete_projet, name='delete_projet'),

    path('Equipes', views.list_equipes, name='list_equipes'),
    path('createEquipe/', views.create_equipe, name='create_equipe'),
    path('<int:equipe_id>/detail_equipe', views.detail_equipe, name='detail_equipe'),
    path('<int:equipe_id>/edit_equipe/', views.edit_equipe, name='edit_equipe'),
    path('<int:equipe_id>/delete_equipe/', views.delete_equipe, name='delete_equipe'),
    
   
    path('services/', views.TtService, name='TtService'),
    path('createService/', views.create_service, name='create_service'),
    path('<int:service_id>/detailService/', views.detail_service, name='detail_service'),
    path('<int:service_id>/editService/', views.edit_service, name='edit_service'),
    path('<int:service_id>/deleteService/', views.delete_service, name='delete_service'),


    path('', views.indexA, name='indexA'),
    path('inscription_client/', views.inscription_client, name='inscription_client'),
    #detail
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name = 'logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projet/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ArtyProd/', include('ArtyProd.urls')),
    path('about', views.about, name='about'),
   path('', views.about,name='about'),
    path('home/', views.home,name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name = 'logout'),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

ArtyProd/models.py
from django.utils import  timezone

from django.contrib.auth.models import  User
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
import datetime

# Create your models here.

from django.contrib.auth.models import User, Group

class Personnel(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100, default='')
    date_naissance = models.DateField(default=datetime.date.today)
    photo = models.ImageField(upload_to='photosProfil/', blank=True, null=True)
    cv = models.FileField(upload_to='cv/', blank=True, null=True)
    date_affectation = models.DateField(null=True, default=datetime.date.today)
    profil_linkedin_ou_site_personnel = models.URLField(blank=True)

    def __str__(self):
        return f"{self.nom} {self.prenom}"


    

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=255, default="")
    adresse = models.CharField(max_length=255, default="")
    telephone = models.CharField(max_length=255, default="")
    email = models.EmailField(max_length=255, default="")
    Img = models.ImageField(upload_to='media/', null=True, blank=True)

    def __str__(self):
        return f'{self.user.username}, {self.adresse}, {self.telephone}'

    def save(self, *args, **kwargs):
        # Vérifier si le groupe "Client" existe, sinon le créer
        group, created = Group.objects.get_or_create(name='Client')
        self.user.groups.add(group)
        super().save(*args, **kwargs)


class DemandeProjet(models.Model):
    libelle = models.CharField(max_length=50)
    description = models.TextField()
    date_demande = models.DateTimeField(auto_now_add=True)
    service = models.ForeignKey('Service', on_delete=models.CASCADE)
    equipe = models.ForeignKey('Equipe', on_delete=models.CASCADE, null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True, blank=True)
    STATUT_CHOICES = [
        ('En attente', 'En attente'),
        ('En cours', 'En cours'),
        ('Terminé', 'Terminé')
    ]
    statut = models.CharField(max_length=20, choices=STATUT_CHOICES)
    
    def __str__(self):
        return self.libelle
    









class Projet(models.Model):
    libelle = models.CharField(max_length=50, default='')  # Définir la valeur par défaut à une chaîne vide ou une autre valeur appropriée
    description = models.TextField(default='')
    date_debut = models.DateField(default=datetime.date.today)
    date_fin = models.DateField(default=datetime.date.today)
    acheve = models.BooleanField(default=False)
    image = models.ImageField(upload_to='media/', blank=True)
    service = models.ForeignKey('Service', on_delete=models.CASCADE, null=True, blank=True)
    equipe = models.ForeignKey('Equipe', on_delete=models.CASCADE, null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.libelle



class Service(models.Model):
    TYPE_CHOICES = [
        ('Design Graphique', 'Design Graphique'),
        ('Design Web', 'Design Web'),
        ('SC', 'Scénarisation'),
    ]

    nom = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField()
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    image = models.ImageField( null=True, blank=True)

    def str(self):
        return self.nom

class Portfolio(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
class Detail(models.Model):
    fichier = models.FileField(upload_to='media/')

    def __str__(self):
        return f'{self.fichier}'



class Equipe(models.Model):
    nom = models.CharField(max_length=25)
    membres = models.ManyToManyField(Personnel)
    
    
    def __str__(self):
        return f'{self.nom}, {self.membres}'
class Contact(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()
    phoneNumber=models.CharField(max_length=12)
    description=models.TextField()
    def __str__(self) :
  
        return f'Message from {self.name}'
    
class Panier(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_ajout = models.DateTimeField(default=timezone.now)    
    quantite = models.IntegerField(default=1)
    def total_prix(self):
        return sum([f.prix for f in self.formations.all() if f.prix])

ArtyProd/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Personnel, Projet, Service, Detail, Equipe
from .models import DemandeProjet
class PersonnelForm(forms.ModelForm):
     class Meta : 
        model = Personnel
        fields = "__all__"

class ProjetForm(forms.ModelForm):
     class Meta : 
        model = Projet
        fields = "__all__" #pour tous les champs de la table


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'


class DetailForm(forms.ModelForm):
    class Meta:
        model = Detail
        fields = '__all__'


class EquipeForm(forms.ModelForm):
    class Meta:
        model = Equipe
        fields = '__all__'
class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(label='Prénom')
    last_name = forms.CharField(label='Nom')
    email = forms.EmailField(label='Adresse e-mail')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + \
            ('first_name', 'last_name', 'email')

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ClientCreationForm(UserCreationForm):
    nom = forms.CharField(max_length=255)
    adresse = forms.CharField(max_length=255)
    telephone = forms.CharField(max_length=255)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'nom', 'adresse', 'telephone', 'email']
class DemandeProjetForm(forms.ModelForm):
    class Meta:
        model = DemandeProjet
        exclude = ['client', 'date_demande', 'statut', 'equipe']
        labels = {
            'libelle': 'Libellé',
            'description': 'Description',
            'service': 'Service',
        } 

class DemandeProjetEditForm(forms.ModelForm):
    class Meta:
        model = DemandeProjet
        exclude = ['client', 'libelle', 'description', 'service', 'date_demande' ]
        labels = {
            'statut': 'Statut',
            'equipe': 'Equipe',
        } 

ArtyProd/templates/demandeprojet.html
{% extends 'navbar.html' %}
{% block title %} Demande Projet {% endblock %}
{% load static %}
{% block content %}
<br><br>

<section class="section-add-service">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Demander Projet</h2>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_libelle">Libelle :</label><br>
                        {{ form.libelle }}
                    </div>
                    <div class="form-group">
                        <label for="id_description">Description :</label><br>
                        {{ form.description }}
                    </div>
                    <div class="form-group">
                        <label for="id_service">Service :</label><br>
                        {{ form.service }}
                    </div>
                    <div class="form-group">
                        <label for="id_equipe">Equipe :</label><br>
                        {{ form.equipe }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Enregistrer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <br><br>
</section>
<style>
    .section-add-service {
        min-height: calc(100vh - 200px);
    }

    .card {
        max-width: 600px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
    }

    .card-header {
        margin-bottom: 20px;
    }

    .card-header h2 {
        font-size: 30px;
        font-weight: bold;
        margin: 0;
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    input[type="text"],
    textarea {
        font-size: 16px;
        border-radius: 5px;
        border: 1px solid #ccc;
    }

    textarea {
        height: 150px;
    }
</style>

{% endblock %}

ArtyProd/templates/inscription_client.html
<!-- inscription_client.html -->

<h2>Inscription Client</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit">Inscription</button>
</form>

ArtyProd/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>ArtyProd</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/static/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner"
        class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Topbar Start -->
    <div class="container-fluid bg-dark px-5 d-none d-lg-block">
        <div class="row gx-0">

            <div class="col-lg-4 text-center text-lg-end">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i
                            class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i
                            class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i
                            class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i
                            class="fab fa-instagram fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href=""><i
                            class="fab fa-youtube fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar & Hero Start -->
    <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
        <a href="" class="navbar-brand p-0">
            <h1 class="text-primary m-0"><i class="fa fa-map-marker-alt me-3"></i>ArtyProd</h1>
            <!-- <img src="/static/img/logo.png" alt="Logo"> -->
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="about.html" class="nav-item nav-link active">About</a>
                <a href="{% url 'TtService' %}" class="nav-item nav-link">Service</a>
                <a href="{% url 'TtPersonnel' %}" class="nav-item nav-link">personnel</a>

                <a href="{% url 'list_equipes' %}" class="nav-item nav-link">equipes</a>
                <a href="{% url 'TtProjet' %}" class="nav-item nav-link">projet</a>

                <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>



                {% if user.is_authenticated %}

                <a href="{% url 'demande_projet' %}" class="nav-item nav-link">demande_projet</a>



                {% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="nav-item nav-link">Déconnexion</a></li>



                {% else %}
                <li><a href="{% url 'login' %}" class="btn btn-primary rounded-pill py-2 px-4">Connexion</a></li>

                <li class="nav-item active">
                    <a href="{% url 'register' %}" class="btn btn-primary rounded-pill py-2 px-4">Inscrit</a>
                </li>
                {% endif %}
            </div>





        </div>


        </div>
    </nav>

    <div class="container-fluid bg-primary py-5 mb-5 hero-header">

    </div>

    <!-- Navbar & Hero End -->






    {% block content %} {% endblock %}
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Company</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                    <a class="btn btn-link" href="">FAQs & Help</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Gallery</h4>
                    <div class="row g-2 pt-2">
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/static/img/package-1.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/static/img/package-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/static/img/package-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/static/img/package-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/static/img/package-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid bg-light p-1" src="/static/img/package-1.jpg" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Newsletter</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text"
                            placeholder="Your email">
                        <button type="button"
                            class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/lib/wow/wow.min.js"></script>
    <script src="/static/lib/easing/easing.min.js"></script>
    <script src="/static/lib/waypoints/waypoints.min.js"></script>
    <script src="/static/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="/static/lib/tempusdominus/js/moment.min.js"></script>
    <script src="/static/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="/static/js/main.js"></script>
</body>

</html>